'use client';

import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowUpRight, ArrowDown, ArrowLeft, ArrowRight, Copy, Check, Plus, Minus, Maximize2, ZoomIn, ZoomOut, Menu } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Sheet, SheetContent, SheetTitle, SheetTrigger, SheetClose } from '@/components/ui/sheet';
import { MotionRoot, Marquee, useMotion, useGSAP } from './motion';
import { PageReadiness, ReliableImage } from './readiness';
import { Ledger } from './ledger';
import data from '@/content/public.json';

const projects = data.projects;
type Project = typeof projects[number];
type Screen = Project['gallery'][number];
const portrait = '/images/vinh-portrait.webp';
const projectImages:Record<string,{home:string,detail:string}> = {
 'debt-ledger':{home:'01-home-debtledger.png',detail:'01-detail-debtledger.png'},
 mseller:{home:'02-home-mseller.png',detail:'02-detail-mseller.png'},
 beerich:{home:'03-home-beerich.png',detail:'03-detail-beerich.png'},
 moodify:{home:'04-home-moodify.png',detail:'04-detail-moodify.png'},
};
const links = [['Work','/#work'],['Domains','/#domains'],['Thinking','/#thinking'],['About','/about'],['Contact','/#contact']];

function Inline({text}:{text:string}) { return <>{text.split(/(\*\*.*?\*\*)/g).map((t,i)=>t.startsWith('**')?<strong key={i}>{t.slice(2,-2)}</strong>:t)}</>; }
export function Prose({text}:{text:string}) { return <>{text.split(/\n\n+/).filter(Boolean).map((b,i)=>{
 if(b.startsWith('|')) { const rows=b.split('\n').filter(l=>l.startsWith('|')).map(l=>l.replace(/^\||\|$/g,'').split('|').map(v=>v.trim()));return <div className="table-region" key={i} role="region" aria-label="Detailed explanation" tabIndex={0}><Table><TableHeader><TableRow>{rows[0].map((c,j)=><TableHead key={j}><Inline text={c}/></TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice(2).map((row,k)=><TableRow key={k}>{row.map((c,j)=><TableCell key={j}><Inline text={c}/></TableCell>)}</TableRow>)}</TableBody></Table></div>; }
 if(/^\d+\. /.test(b))return <ol key={i}>{b.split('\n').map((l,j)=><li key={j}><Inline text={l.replace(/^\d+\. /,'')}/></li>)}</ol>;
 if(b.startsWith('- '))return <ul key={i}>{b.split('\n').map((l,j)=><li key={j}><Inline text={l.replace(/^- /,'')}/></li>)}</ul>;
 return <p key={i}><Inline text={b.replace(/\n/g,' ')}/></p>;
 })}</>; }

function Header() {
 const [active,setActive]=useState('');
 useEffect(()=>{
  if(location.pathname==='/about')setActive('About'); else if(location.pathname.startsWith('/work/'))setActive('Work');
  const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)setActive(e.target.id.charAt(0).toUpperCase()+e.target.id.slice(1));}),{rootMargin:'-15% 0px -60% 0px',threshold:0});
  ['work','domains','thinking','contact'].forEach(id=>{const e=document.getElementById(id);if(e)observer.observe(e);});
  return()=>observer.disconnect();
 },[]);
 return <header className="site-header"><a href="/" className="wordmark" aria-label="Vinh Nguyen home">vinh<span className="brand-dot">.</span><span className="brand-name">nguyen</span></a><nav aria-label="Main navigation">{links.map(([name,href])=><a key={name} href={href} aria-current={active===name?'location':undefined}>{name}</a>)}</nav><a href="/about#experience" className="experience-link">About my work <ArrowUpRight size={15}/></a><Sheet><SheetTrigger asChild><button className="mobile-menu" aria-label="Open navigation"><Menu size={24}/></button></SheetTrigger><SheetContent className="mobile-sheet"><SheetTitle>Explore the portfolio</SheetTitle><nav aria-label="Mobile navigation">{links.map(([name,href])=><SheetClose key={name} asChild><a href={href}>{name}<ArrowUpRight size={22}/></a></SheetClose>)}</nav></SheetContent></Sheet></header>;
}
function Footer(){const {mode,setMode}=useMotion();return <footer className="site-footer"><a href="/">Vinh Nguyen <span>— Product thinking, business analysis, and UX.</span></a><div className="footer-tools"><Select value={mode} onValueChange={v=>setMode(v as 'System'|'Reduced'|'Full')}><SelectTrigger aria-label="Motion preference" className="motion-select"><span>Motion: </span><SelectValue>{mode}</SelectValue></SelectTrigger><SelectContent className="motion-options">{['System','Reduced','Full'].map(v=><SelectItem value={v} key={v}>{v}</SelectItem>)}</SelectContent></Select><a href="#top">Back to top ↑</a></div></footer>;}
function Shell({children}:{children:ReactNode}) {return <MotionRoot><a href="#main" className="skip">Skip to content</a><Header/>{children}<Footer/><PageReadiness/></MotionRoot>;}
function Contact(){
 const [status,setStatus]=useState('');
 async function copy(){try{await navigator.clipboard.writeText('jvinh209@gmail.com');setStatus('Email copied.');}catch{setStatus('Please copy jvinh209@gmail.com.');}}
 return <section id="contact" className="contact section"><div className="section-label"><span>CONTINUE THE CONVERSATION</span><span>VIETNAM · UTC+7</span></div><div className="contact-grid"><div><h2><span>There is always</span><span>another <em>good question.</em></span></h2><a href="mailto:jvinh209@gmail.com" className="email-link" aria-label="Email Vinh at jvinh209@gmail.com">jvinh209@gmail.com <ArrowUpRight/></a></div><div className="contact-note"><p>Have a perspective on product, design, or one of these projects? I’d enjoy exchanging ideas.</p><div className="contact-actions"><a href="https://www.linkedin.com/in/jvinh209" target="_blank" rel="noopener noreferrer" aria-label="Connect on LinkedIn (opens in a new tab)">Connect on LinkedIn <ArrowUpRight size={16}/></a><button onClick={copy}>{status==='Email copied.'?<Check size={15}/>:<Copy size={15}/>} Copy email</button></div><p className="copy-status" role="status">{status}</p></div></div></section>;
}

function ProjectCover({project:p,hero=false,compact=false}:{project:Project,hero?:boolean,compact?:boolean}){
 const image=projectImages[p.slug];
 const main=p.gallery[p.slug==='moodify'?7:0];
 const secondary=p.gallery[p.slug==='moodify'?3:p.slug==='mseller'?4:1];
 const frame=(screen:{src:string,width:number,height:number},role:string,essential=false)=><div className={`visual-frame visual-${role}`} style={{aspectRatio:`${screen.width} / ${screen.height}`}}><ReliableImage src={screen.src} alt="" aria-hidden="true" width={screen.width} height={screen.height} loading={essential?'eager':'lazy'} decoding="async" data-entry-media={essential?'true':undefined}/></div>;
 return <div className={`project-visual visual-${p.slug} ${hero?'visual-hero':''} ${compact?'visual-compact':''}`}>
  <div className="visual-label"><span>{p.name}</span><span>{p.number} / SELECTED WORK</span></div>
  <div className="visual-canvas">{compact?<>{frame(main,'main',hero)}{frame(p.slug==='beerich'?p.detail:secondary,'support')}{p.slug==='debt-ledger'&&frame(p.detail,'detail')}{p.slug==='beerich'&&frame(p.gallery[2],'third')}</>:<div className="visual-frame" style={{inset:0,width:'100%',height:'100%',maxWidth:'none',border:0,borderRadius:0,boxShadow:'none',background:'transparent',overflow:'visible'}}><ReliableImage className="visual-main" src={`/images/projects/${hero?image.detail:image.home}`} alt="" aria-hidden="true" width={hero?1672:1448} height={hero?941:1086} loading={hero?'eager':'lazy'} decoding="async" data-entry-media={hero?'true':undefined} data-project-media={hero?'detail':'home'} style={{position:'static',width:'100%',height:'100%',maxWidth:'none',objectFit:'contain',objectPosition:'center',transform:'none',transition:'inherit'}}/></div>}</div>
  <div className="visual-caption"><span>{p.slug==='debt-ledger'?'BALANCE · HISTORY · STATUS':p.slug==='mseller'?'THE WORKSPACE & THE NEXT STEP':p.slug==='beerich'?'PRESENT · INVESTMENT · FUTURE':'A CALMER WAY TO BEGIN'}</span><ArrowUpRight size={20}/></div>
 </div>;
}
function WorkShowcase(){
 const scope=useRef<HTMLDivElement>(null),stage=useRef<HTMLDivElement>(null);
 const [active,setActive]=useState(0);const {reduced,ready}=useMotion();
 useGSAP(({gsap,ScrollTrigger})=>{if(!ready||reduced)return;const mm=gsap.matchMedia();mm.add('(min-width: 1000px) and (min-height: 650px)',()=>{
  gsap.utils.toArray<HTMLElement>('.work-item',scope.current).forEach((el,i)=>ScrollTrigger.create({trigger:el,start:'top 55%',end:'bottom 55%',onEnter:()=>setActive(i),onEnterBack:()=>setActive(i)}));
 });return()=>mm.revert();},{scope,dependencies:[ready,reduced],revertOnUpdate:true});
 useGSAP(({gsap,ScrollTrigger})=>{if(!reduced&&ready&&stage.current)gsap.fromTo(stage.current,{opacity:.5,y:10},{opacity:1,y:0,duration:.4,ease:'power2.out',clearProps:'all'});},{scope,dependencies:[active,reduced,ready],revertOnUpdate:true});
 return <div className="work-showcase" ref={scope}><div className="work-stage"><div ref={stage}><a className="cover-link" href={`/work/${projects[active].slug}`} aria-label={`Explore the ${projects[active].name} case`} tabIndex={-1}><ProjectCover project={projects[active]}/></a><div className="stage-index" aria-hidden="true">{projects.map((p,i)=><span key={p.slug} className={i===active?'active':''}>{p.number} — {p.name}</span>)}</div></div></div><div className="work-stories">{projects.map((p,i)=><article key={p.slug} className={`work-item ${i===active?'active':''}`}><a className="inline-cover cover-link" href={`/work/${p.slug}`} aria-label={`Explore the ${p.name} case`}><ProjectCover project={p}/></a><div className="project-summary"><p className="eyebrow">{p.number} / {p.focus.toUpperCase()}</p><h3><a href={`/work/${p.slug}`}>{p.name}<ArrowUpRight size={24}/></a></h3><p className="project-line">{p.line}</p><p className="project-description">{p.description}</p><a className="text-link case-link" href={`/work/${p.slug}`} aria-label={`Explore the ${p.name} case`}>Explore the case <ArrowUpRight size={19}/></a></div></article>)}</div></div>;
}
function Domains(){return <section id="domains" className="domains section"><div className="section-label"><span>DOMAIN PERSPECTIVES</span><span>CONTEXT CHANGES THE QUESTION</span></div><h2>Different domains.<br/>A shared interest in <em>clarity.</em></h2><div className="domain-grid">{data.domains.map((d,i)=><article className="domain-panel" key={d.slug}><div className="domain-rule"/><span className="small-number">0{i+1}</span><h3>{d.title}</h3><p>{d.text}</p><blockquote>{d.question}</blockquote><a className="text-link" href={`/work/${d.slug}`}>Explore {d.name}<ArrowUpRight size={17}/></a></article>)}</div></section>;}
const sketchLabels=[['Moment','Task','Context'],['Information','Decision','Action'],['Event','Rule','State'],['Option A','Trade-off','Option B'],['Pending','Recover','Continue'],['Question','Observe','Learn']];
function Thinking(){
 const scope=useRef<HTMLDivElement>(null),sketch=useRef<HTMLDivElement>(null);const [active,setActive]=useState(0);const {reduced,ready}=useMotion();
 useGSAP(({gsap,ScrollTrigger})=>{if(!ready||reduced)return;const mm=gsap.matchMedia();mm.add('(min-width: 1000px) and (min-height: 650px)',()=>{gsap.utils.toArray<HTMLElement>('.thinking-step',scope.current).forEach((el,i)=>ScrollTrigger.create({trigger:el,start:'top 55%',end:'bottom 55%',onEnter:()=>setActive(i),onEnterBack:()=>setActive(i)}));});return()=>mm.revert();},{scope,dependencies:[ready,reduced],revertOnUpdate:true});
 useGSAP(({gsap,ScrollTrigger})=>{if(!reduced&&ready)gsap.from(sketch.current,{y:8,opacity:.5,duration:.3,clearProps:'all'});},{scope,dependencies:[active,reduced,ready],revertOnUpdate:true});
 return <section id="thinking" className="thinking"><div className="section"><div className="section-label"><span>HOW I THINK</span><span>A PRACTICE, NOT A FIXED FORMULA</span></div><h2>The screen is one part<br/>of <em>the reasoning.</em></h2><p className="thinking-intro">I use a few recurring questions to move from an unclear request to an experience a team can discuss, build, and evaluate. The depth of each step depends on the problem. These are the questions I bring to the work.</p><div className="thinking-layout" ref={scope}><div className="thinking-support" aria-hidden="true"><div ref={sketch}><span className="thinking-count">0{active+1}<span>/ 06</span></span><div className="reasoning-sketch">{sketchLabels[active].map((s,i)=><div key={s}><span>{s}</span>{i<2&&<ArrowDown size={24}/>}</div>)}</div><p>{data.steps[active].question}</p></div></div><div className="thinking-steps">{data.steps.map((step,i)=><article className={`thinking-step ${active===i?'active':''}`} key={step.number}><span className="small-number">{step.number}</span><h3>{step.title}.</h3><p>{step.description}</p><p className="example-question">{step.question}</p></article>)}</div></div></div></section>;
}
export function HomePage(){return <Shell><main id="main"><section id="top" className="hero"><div className="hero-top"><p className="eyebrow">BUSINESS ANALYST · PRODUCT OWNER · UX THINKING</p><span className="hero-edition">SELECTED WORK & PERSPECTIVES</span></div><div className="hero-grid"><div className="hero-copy"><h1 tabIndex={-1}><span className="hero-line">Complex<br/>domains.</span><em className="hero-line">Clear experiences.</em></h1><p className="hero-description">I'm Vinh Nguyen. I connect business rules, product decisions, and user experience to make complex services easier to understand and use. My work spans personal finance, merchant operations, and debt tracking, alongside an exploration of digital wellbeing.</p><div className="hero-actions"><a href="#work" className="primary-link">Explore the work <ArrowDown size={17}/></a><a href="#thinking" className="text-link">How I think <ArrowUpRight size={17}/></a></div></div><figure className="portrait-composition"><div className="portrait-halo" aria-hidden="true"/><div className="portrait-mask"><div className="portrait-drift"><ReliableImage src={portrait} alt="Vinh Nguyen wearing a blue suit and glasses" width="800" height="1200" fetchPriority="high" data-entry-media="true"/></div></div><figcaption><span>Vinh Nguyen</span><span>THE PERSON BEHIND THE WORK</span></figcaption></figure></div><div className="hero-bottom"><span>Based in Vietnam</span><span className="hero-editorial">Every screen begins with a decision.</span><a href="#work" aria-label="Scroll to selected work"><ArrowDown size={19}/></a></div></section><Marquee/>
 <section id="work" className="work section"><div className="section-label"><span>SELECTED WORK / 01–04</span><span>FROM THE SCREEN TO THE THINKING</span></div><div className="work-heading"><h2>Four projects.<br/>Different decisions<br/>to make <em>clearer.</em></h2><p>From understanding a balance to choosing a first step, each project explores how an experience becomes useful.</p></div><WorkShowcase/></section><Domains/><Thinking/>
 <section className="personal section"><div className="personal-portrait"><ReliableImage src={portrait} alt="Vinh Nguyen" width="800" height="1200" loading="lazy"/></div><div><p className="eyebrow">THE PERSON BEHIND THE WORK</p><h2>I’m interested in<br/>the decisions<br/><em>behind the interface.</em></h2><div className="body-copy"><Prose text={data.personal}/></div><a className="text-link" href="/about">About my work <ArrowUpRight size={18}/></a></div></section><Contact/></main></Shell>;}

function ScreenViewer({screen,showNote}:{screen:Screen,showNote:boolean}){
 const [zoom,setZoom]=useState(false);
 const board=screen.width>screen.height;
 return <figure className="screen-figure"><Dialog onOpenChange={()=>setZoom(false)}><DialogTrigger asChild><button className="screen-button" aria-label={`Enlarge ${screen.sourceProject}: ${screen.caption}`}><div className="screen-image"><ReliableImage src={screen.src} alt={screen.alt} width={screen.width} height={screen.height} loading="lazy"/></div><span className="enlarge"><Maximize2 size={15}/> Enlarge screen</span></button></DialogTrigger><DialogContent className="screen-dialog"><DialogTitle>{screen.sourceProject} — {screen.caption}</DialogTitle><DialogDescription>{screen.kind}. {screen.annotation||'Explore the interface detail.'}</DialogDescription><button className="viewer-zoom" onClick={()=>setZoom(!zoom)}>{zoom?<ZoomOut size={16}/>:<ZoomIn size={16}/>} {zoom?'Fit image':'Enlarge detail'}</button><div className={`viewer-image ${zoom?'zoomed':''} ${board?'board-viewer':''}`} tabIndex={0} role="region" aria-label="Enlarged screen"><ReliableImage src={screen.src} alt={screen.alt} width={screen.width} height={screen.height}/></div></DialogContent></Dialog><figcaption><span>{screen.kind}</span>{screen.caption}</figcaption>{showNote&&screen.annotation&&<p className="image-annotation"><span>↳</span>{screen.annotation}</p>}</figure>;
}
function Gallery({project:p}:{project:Project}){
 const [notes,setNotes]=useState(false);const scope=useRef<HTMLDivElement>(null);const {reduced}=useMotion();
 useGSAP(({gsap,ScrollTrigger})=>{if(notes&&!reduced)gsap.from('.image-annotation',{y:6,opacity:.5,duration:.28,stagger:.04,clearProps:'all'});ScrollTrigger.refresh();},{scope,dependencies:[notes,reduced],revertOnUpdate:true});
 return <div ref={scope}><div className="gallery-tools"><p>Explore the interface, then the reasoning.</p><button className="notes-toggle" onClick={()=>setNotes(!notes)} aria-expanded={notes} aria-controls={`gallery-${p.slug}`}>{notes?<Minus size={16}/>:<Plus size={16}/>} {notes?'Hide notes':'See the thinking'}</button></div><div className="screen-gallery" id={`gallery-${p.slug}`}>{p.gallery.map(screen=><ScreenViewer key={screen.src} screen={screen} showNote={notes}/>)}</div><div className="screen-reading"><h3>A closer reading</h3><ul>{p.annotations.map(note=><li key={note}>{note}</li>)}</ul></div><div className="original-board"><ScreenViewer screen={p.original} showNote={false}/></div></div>;
}
function DecisionNotes({project:p}:{project:Project}){return <div className="decision-notes">{p.decisions.map((n,i)=><article className="decision-note" key={n.question}><span className="eyebrow">DECISION {String(i+1).padStart(2,'0')}</span><h3>{n.question}</h3><dl>{[['Question',n.question],['Options',n.options],['My reasoning',n.reasoning],['What I would check',n.check]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></article>)}</div>;}
function MoodifyJourney({project:p}:{project:Project}){return <div className="moodify-journey"><p className="eyebrow">A PROPOSED JOURNEY THROUGH THE EXPERIENCE</p><div className="journey-trunk"><div>Welcome & introduction</div><ArrowDown size={18}/><div>Optional onboarding <small>Complete or skip</small></div><ArrowDown size={18}/><div>Personal overview</div></div><div className="journey-branches"><div><h3>Explore a quiet activity</h3><p>Self-guided content → meditation discovery</p><ReliableImage src={p.gallery[5].src} alt={p.gallery[5].alt} width={220} height={478} loading="lazy"/><div className="next-iteration"><span>Next iteration</span>Session detail</div></div><div><h3>Explore connection</h3><p>Connection → practitioner profile</p><ReliableImage src={p.gallery[6].src} alt="Example practitioner profile interface" width={221} height={556} loading="lazy"/><div className="next-iteration"><span>Next iteration</span>Meeting request or message</div></div></div></div>;}

export function CasePage({slug}:{slug:string}){
 const index=projects.findIndex(p=>p.slug===slug),p=projects[index];if(!p)return null;const next=projects[(index+1)%projects.length];
 return <Shell><main id="main"><section id="top" className="case-opening section"><a href="/#work" className="back-link"><ArrowLeft size={16}/> Selected work</a><p className="eyebrow">{p.eyebrow}</p><h1 tabIndex={-1}>{p.title}</h1><p className="case-deck">{p.deck}</p><dl className="case-facts">{p.fields.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="case-hero-media"><ProjectCover project={p} hero/></div></section><div className="case-body section"><aside className="case-index"><p className="eyebrow">IN THIS STORY</p><nav aria-label="Case study sections">{p.sections.map((s,i)=><a key={s.id} href={`#${s.id}`}><span>{String(i+1).padStart(2,'0')}</span>{s.title}</a>)}</nav></aside><div className="case-prose"><details className="mobile-index"><summary>On this page</summary><nav>{p.sections.map(s=><a key={s.id} href={`#${s.id}`}>{s.title}</a>)}</nav></details>{p.sections.map((s,i)=><section id={s.id} className={'story-section '+(s.title==='Personal reflection'?'personal-note':'')} key={s.id}><p className="eyebrow section-number">{String(i+1).padStart(2,'0')} / {p.name.toUpperCase()}</p><h2>{s.title}</h2>{s.kind==='journey'&&<MoodifyJourney project={p}/>}<Prose text={s.body}/>{s.kind==='ledger'&&<Ledger/>}{s.kind==='gallery'&&<Gallery project={p}/>} {s.kind==='decisions'&&<DecisionNotes project={p}/>}</section>)}</div></div><section className="next-case section has-preview"><span className="eyebrow">NEXT CASE / {next.number}</span><a href={`/work/${next.slug}`}><div className="next-case-image"><ProjectCover project={next} compact/></div><div><span>{next.name}</span><h2>{next.line}</h2></div><ArrowRight/></a></section><Contact/></main></Shell>;
}
export function AboutPage(){return <Shell><main id="main"><section id="top" className="about-opening section"><div><p className="eyebrow">ABOUT VINH</p><h1 tabIndex={-1}>I’m interested in<br/>the decisions<br/><em>behind the interface.</em></h1><div className="body-copy"><Prose text={data.about.Opening}/></div></div><figure className="about-portrait"><ReliableImage src={portrait} alt="Vinh Nguyen in a blue suit" width="800" height="1200" data-entry-media="true"/><figcaption>Vinh Nguyen · Vietnam, UTC+7</figcaption></figure></section><div className="about-body section">{Object.entries(data.about).filter(([key])=>key!=='Opening').map(([title,body],i)=><section className="about-section" id={i===1?'experience':undefined} key={title}><p className="eyebrow">0{i+1} / ABOUT ME</p><div><h2>{title}</h2><Prose text={body}/></div></section>)}</div><Contact/></main></Shell>;}
export function NotFoundPage(){return <Shell><main id="main" className="not-found section"><span id="top" className="eyebrow">404 / A DIFFERENT DIRECTION</span><h1 tabIndex={-1}>Let’s get back<br/>to <em>the work.</em></h1><p>This page isn't here. You can explore my selected projects or get in touch.</p><div className="hero-actions"><a href="/#work" className="primary-link">Selected work <ArrowRight size={17}/></a><a href="/#contact" className="text-link">Contact Vinh <ArrowUpRight size={17}/></a></div></main></Shell>;}
