import { CTA } from '../components/CTA';
import { useRef, useState } from 'react';
import { ArrowUpRight, ArrowDown, ArrowLeft, ArrowRight, Plus, Minus, Maximize2, ZoomIn, ZoomOut } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from '../components/ui/dialog';
import { Shell, Contact } from '../components/Shell';
import { Prose } from '../components/Prose';
import { ReliableImage } from '../components/readiness';
import { useMotion, useGSAP } from '../components/motion';
import { Ledger } from '../components/ledger';
import { ProjectCover } from '../components/work/ProjectCover';
import type { Project, ProjectPreview, Screen } from '../content/types';
function ScreenViewer({screen,showNote}:{screen:Screen,showNote:boolean}){
 const [zoom,setZoom]=useState(false);
 const board=screen.width>screen.height;
 return <figure className="screen-figure"><Dialog onOpenChange={()=>setZoom(false)}><DialogTrigger asChild><button className="screen-button" aria-label={`Enlarge ${screen.sourceProject}: ${screen.caption}`}><div className="screen-image"><ReliableImage src={screen.src} alt={screen.alt} width={screen.width} height={screen.height} loading="lazy"/></div><span className="enlarge"><Maximize2 size={15}/> Enlarge screen</span></button></DialogTrigger><DialogContent className="screen-dialog" data-lenis-prevent><DialogTitle>{screen.sourceProject} — {screen.caption}</DialogTitle><DialogDescription>{screen.kind}. {screen.annotation||'Explore the interface detail.'}</DialogDescription><button className="viewer-zoom" onClick={()=>setZoom(!zoom)}>{zoom?<ZoomOut size={16}/>:<ZoomIn size={16}/>} {zoom?'Fit image':'Enlarge detail'}</button><div className={`viewer-image ${zoom?'zoomed':''} ${board?'board-viewer':''}`} tabIndex={0} role="region" aria-label="Enlarged screen"><ReliableImage src={screen.src} alt={screen.alt} width={screen.width} height={screen.height}/></div></DialogContent></Dialog><figcaption><span>{screen.kind}</span>{screen.caption}</figcaption>{showNote&&screen.annotation&&<p className="image-annotation"><span>↳</span>{screen.annotation}</p>}</figure>;
}
function Gallery({project:p}:{project:Project}){
 const [notes,setNotes]=useState(false);const scope=useRef<HTMLDivElement>(null);const {reduced}=useMotion();
 useGSAP(({gsap,ScrollTrigger})=>{if(notes&&!reduced)gsap.from('.image-annotation',{y:6,opacity:.5,duration:.28,stagger:.04,clearProps:'all'});ScrollTrigger.refresh();},{scope,dependencies:[notes,reduced],revertOnUpdate:true});
 return <div ref={scope}><div className="gallery-tools"><p>Explore the interface, then the reasoning.</p><button className="notes-toggle" onClick={()=>setNotes(!notes)} aria-expanded={notes} aria-controls={`gallery-${p.slug}`}>{notes?<Minus size={16}/>:<Plus size={16}/>} {notes?'Hide notes':'See the thinking'}</button></div><div className="screen-gallery" id={`gallery-${p.slug}`}>{p.gallery.map(screen=><ScreenViewer key={screen.src} screen={screen} showNote={notes}/>)}</div><div className="screen-reading"><h3>A closer reading</h3><ul>{p.annotations.map(note=><li key={note}>{note}</li>)}</ul></div><div className="original-board"><ScreenViewer screen={p.original} showNote={false}/></div></div>;
}
function DecisionNotes({project:p}:{project:Project}){return <div className="decision-notes">{p.decisions.map((n,i)=><article className="decision-note" key={n.question}><span className="eyebrow">DECISION {String(i+1).padStart(2,'0')}</span><h3>{n.question}</h3><dl>{[['Question',n.question],['Options',n.options],['My reasoning',n.reasoning],['What I would check',n.check]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></article>)}</div>;}
function MoodifyJourney({project:p}:{project:Project}){return <div className="moodify-journey"><p className="eyebrow">A PROPOSED JOURNEY THROUGH THE EXPERIENCE</p><div className="journey-trunk"><div>Welcome & introduction</div><ArrowDown size={18}/><div>Optional onboarding <small>Complete or skip</small></div><ArrowDown size={18}/><div>Personal overview</div></div><div className="journey-branches"><div><h3>Explore a quiet activity</h3><p>Self-guided content → meditation discovery</p><ReliableImage src={p.gallery[5].src} alt={p.gallery[5].alt} width={220} height={478} loading="lazy"/><div className="next-iteration"><span>Next iteration</span>Session detail</div></div><div><h3>Explore connection</h3><p>Connection → practitioner profile</p><ReliableImage src={p.gallery[6].src} alt="Example practitioner profile interface" width={221} height={556} loading="lazy"/><div className="next-iteration"><span>Next iteration</span>Meeting request or message</div></div></div></div>;}

export default function CasePage({project:p,next}:{project:Project,next:ProjectPreview}){
 return <Shell><main id="main"><section id="top" className="case-opening section"><CTA href="/#work" className="back-link"><ArrowLeft size={16}/> Selected work</CTA><p className="eyebrow">{p.eyebrow}</p><h1 tabIndex={-1}>{p.title}</h1><p className="case-deck">{p.deck}</p><dl className="case-facts">{p.fields.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="case-hero-media"><ProjectCover project={p} hero/></div></section><div className="case-body section"><aside className="case-index"><p className="eyebrow">IN THIS STORY</p><nav aria-label="Case study sections">{p.sections.map((s,i)=><a key={s.id} href={`#${s.id}`}><span>{String(i+1).padStart(2,'0')}</span>{s.title}</a>)}</nav></aside><div className="case-prose"><details className="mobile-index"><summary>On this page</summary><nav>{p.sections.map(s=><a key={s.id} href={`#${s.id}`}>{s.title}</a>)}</nav></details>{p.sections.map((s,i)=><section id={s.id} className={'story-section '+(s.title==='Personal reflection'?'personal-note':'')} key={s.id}><p className="eyebrow section-number">{String(i+1).padStart(2,'0')} / {p.name.toUpperCase()}</p><h2>{s.title}</h2>{s.kind==='journey'&&<MoodifyJourney project={p}/>}<Prose text={s.body}/>{s.kind==='ledger'&&<Ledger/>}{s.kind==='gallery'&&<Gallery project={p}/>} {s.kind==='decisions'&&<DecisionNotes project={p}/>}</section>)}</div></div><section className="next-case section has-preview"><span className="eyebrow">NEXT CASE / {next.number}</span><a href={`/work/${next.slug}`}><div className="next-case-image"><ProjectCover project={next} compact/></div><div><span>{next.name}</span><h2>{next.line}</h2></div><ArrowRight/></a></section><Contact/></main></Shell>;
}
